export const CONNECT_GAME = "CONNECT_GAME";
export const CONNECT_GAME_SUCCESS = "CONNECT_GAME_SUCCESS";
export const CONNECT_GAME_FAILURE = "CONNECT_GAME_FAILURE";

export const CREATE_GAME = "CREATE_GAME";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const CREATE_GAME_FAILURE = "CREATE_GAME_FAILURE";

export const JOIN_GAME = "JOIN_GAME";
export const JOIN_GAME_SUCCESS = "JOIN_GAME_SUCCESS";
export const JOIN_GAME_FAILURE = "JOIN_GAME_FAILURE";

export const RECEIVE_MENU = "RECEIVE_MENU";
export const RECEIVE_MENU_SUCCESS = "RECEIVE_MENU_SUCCESS";
export const RECEIVE_MENU_FAILURE = "RECEIVE_MENU_FAILURE";

export const ON_MOVE = "ON_MOVE";
export const ON_MOVE_SUCCESS = "ON_MOVE_SUCCESS";
export const ON_MOVE_FAILURE = "ON_MOVE_FAILURE";

export const END_GAME = "END_GAME";
export const END_GAME_SUCCESS = "END_GAME_SUCCESS";
export const END_GAME_FAILURE = "END_GAME_FAILURE";

export const EXIT_GAME = "EXIT_GAME";
export const EXIT_GAME_SUCCESS = "EXIT_GAME_SUCCESS";
export const EXIT_GAME_FAILURE = "EXIT_GAME_FAILURE";

export const RESET_GAME = "RESET_GAME";
export const RESET_GAME_SUCCESS = "RESET_GAME_SUCCESS";
export const RESET_GAME_FAILURE = "RESET_GAME_FAILURE";

export const TRY_AUTH = "TRY_AUTH";
export const TRY_AUTH_SUCCESS = "TRY_AUTH_SUCCESS";
export const TRY_AUTH_FAILURE = "TRY_AUTH_FAILURE";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const SEND = "SEND";
export const SEND_SUCCESS = "SEND_SUCCESS";
export const SEND_FAILURE = "SEND_FAILURE";

export const UPDATE_MENU = "UPDATE_MENU";

export const INIT_GAME = "INIT_GAME";
export const INIT_GAME_SUCCESS = "INIT_GAME_SUCCESS";
export const INIT_GAME_FAILURE = "INIT_GAME_FAILURE";